BOT_TOKEN = "YOUR_BOT_TOKEN_HERE"
ADMIN_ID = 123456789 # Tomar ID
SUPPORT_USERNAME = "@YourSupport"
BOT_NAME = "ProxyStore AI"

FORCE_JOIN_CHANNEL = "@Proxystore999"
FORCE_JOIN_LINK = "https://t.me/Proxystore999"

PRICE_200MB = 60
PRICE_1GB = 150
PRICE_10GB = 500
MORELOGIN_PRICE = 120

BKASH_NUMBER = "01XXXXXXXXX"
NAGAD_NUMBER = "01XXXXXXXXX"
ROCKET_NUMBER = "01XXXXXXXXX"
USDT_ADDRESS = "YOUR_USDT_TRC20"
